In [465]:
import pandas as pd
df=pd.read_csv("traffic_density_202307.csv")

In [466]:
df.head()

,DATE_TIME,LONGITUDE,LATITUDE,GEOHASH,MINIMUM_SPEED,MAXIMUM_SPEED,AVERAGE_SPEED,NUMBER_OF_VEHICLES
0,2023-07-01 00:00:00,29.229126,41.047668,sxkc90,175,79,110,82
1,2023-07-01 00:00:00,29.119263,41.025696,sxk9qs,145,15,85,180
2,2023-07-01 00:00:00,29.053345,40.981750,sxk9jh,56,20,34,12
3,2023-07-01 00:00:00,28.690796,41.058655,sxk3sf,148,18,64,162
4,2023-07-01 00:00:00,28.504028,41.075134,sxk38t,123,6,43,58

In [467]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338909 entries, 0 to 1338908
Data columns (total 8 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   DATE_TIME           1338909 non-null  object
 1   LONGITUDE           1338909 non-null  float64
 2   LATITUDE            1338909 non-null  float64
 3   GEOHASH             1338909 non-null  object
 4   MINIMUM_SPEED       1338909 non-null  int64
 5   MAXIMUM_SPEED       1338909 non-null  int64
 6   AVERAGE_SPEED       1338909 non-null  int64
 7   NUMBER_OF_VEHICLES  1338909 non-null  int64
dtypes: float64(2), int64(4), object(2)
memory usage: 81.7+ MB

In [468]:
df.isnull().sum()

DATE_TIME             0
LONGITUDE             0
LATITUDE              0
GEOHASH               0
MINIMUM_SPEED         0
MAXIMUM_SPEED         0
AVERAGE_SPEED         0
NUMBER_OF_VEHICLES    0
dtype: int64

In [469]:
import numpy as np
df.loc[0:4,'minimum hız']=np.nan
df.head()

,DATE_TIME,LONGITUDE,LATITUDE,GEOHASH,MINIMUM_SPEED,MAXIMUM_SPEED,AVERAGE_SPEED,NUMBER_OF_VEHICLES,minimum hız
0,2023-07-01 00:00:00,29.229126,41.047668,sxkc90,175,79,110,82,NaN
1,2023-07-01 00:00:00,29.119263,41.025696,sxk9qs,145,15,85,180,NaN
2,2023-07-01 00:00:00,29.053345,40.981750,sxk9jh,56,20,34,12,NaN
3,2023-07-01 00:00:00,28.690796,41.058655,sxk3sf,148,18,64,162,NaN
4,2023-07-01 00:00:00,28.504028,41.075134,sxk38t,123,6,43,58,NaN

In [470]:
analiz1=df.groupby("GEOHASH")["minimum hız"].mean()
print(analiz1)

GEOHASH
sx7chk   NaN
sx7chm   NaN
sx7cht   NaN
sx7chw   NaN
sx7chx   NaN
          ..
sxm41s   NaN
sxm41u   NaN
sxm445   NaN
sxm44h   NaN
sxm44k   NaN
Name: minimum hız, Length: 2456, dtype: float64

In [471]:
def fonk(hiz):
  if pd.notnull(hiz):
    return hiz*100
  else:
    return hiz
df["yüz_carpim"]=df["minimum hız"].apply(fonk)
print(df[["minimum hız","yüz_carpim"]])

         minimum hız  yüz_carpim
0                NaN         NaN
1                NaN         NaN
2                NaN         NaN
3                NaN         NaN
4                NaN         NaN
...              ...         ...
1338904          NaN         NaN
1338905          NaN         NaN
1338906          NaN         NaN
1338907          NaN         NaN
1338908          NaN         NaN

[1338909 rows x 2 columns]

In [472]:
import pandas as pd

try:
    # Hata çıkması muhtemel kod buraya yazılır
    df_test = pd.read_csv("traffic_density_202307.csv")
    print("Dosya başarıyla yüklendi!")

except FileNotFoundError:
    # Hata oluşursa burası çalışır
    print("HATA: Dosya bulunamadı, lütfen klasör yolunu kontrol et.")

except Exception as e:
    # Beklenmedik başka bir hata olursa onu yakalar
    print(f"Beklenmedik bir hata oluştu: {e}")

Dosya başarıyla yüklendi!

In [473]:
def fonk(dosya_adi):
  try:
    df=pdf.read_csv("dosya_adi")
    print("Dosya başarıyla yüklendi.")
    return df
  except FileNotFoundError:
    print(f"HATA: {dosya_adi} isimli dosya bulunamadı!")
    return None
  except Exception as e:
    print(f"Beklenmedik bir sorun oluştu: {e}")
    return None
  data = dosyayi_yukle("traffic_density_202307.csv")

In [474]:
def temizlik_hatti(df):
    eksik_sayisi=df["MINIMUM_HIZ"].isnull().sum()
    print(f"Temizlik öncesi eksik veri sayısı: {eksik_sayisi}")

    try:
        # Sütun isimlerini düzelt (Boşlukları _ yap, hepsi büyük harf olsun)
        df.columns = df.columns.str.strip().str.replace(' ', '_').str.upper()
        
        # Artık sütun ismin MINIMUM_HIZ oldu (önceden 'minimum hiz' idi)
        # Eğer 'MINIMUM_SPEED' ile 'MINIMUM_HIZ' aynıysa onları birleştirebiliriz ama 
        # şimdilik mevcut 'MINIMUM_HIZ' üzerinden gidelim:
        
        ortalama_hiz = df['MINIMUM_HIZ'].mean()
        df['MINIMUM_HIZ'] = df['MINIMUM_HIZ'].fillna(ortalama_hiz)
        
        # Negatifleri düzelt
        df['MINIMUM_HIZ'] = df['MINIMUM_HIZ'].apply(lambda x: 0 if x < 0 else x)
        
        print("Temizlik başarıyla tamamlandı.")
        return df
        
    except Exception as e:
        print(f"Hata oluştu: {e}")
        return None

    df.info()

In [475]:
df.head()

,DATE_TIME,LONGITUDE,LATITUDE,GEOHASH,MINIMUM_SPEED,MAXIMUM_SPEED,AVERAGE_SPEED,NUMBER_OF_VEHICLES,minimum hız,yüz_carpim
0,2023-07-01 00:00:00,29.229126,41.047668,sxkc90,175,79,110,82,NaN,NaN
1,2023-07-01 00:00:00,29.119263,41.025696,sxk9qs,145,15,85,180,NaN,NaN
2,2023-07-01 00:00:00,29.053345,40.981750,sxk9jh,56,20,34,12,NaN,NaN
3,2023-07-01 00:00:00,28.690796,41.058655,sxk3sf,148,18,64,162,NaN,NaN
4,2023-07-01 00:00:00,28.504028,41.075134,sxk38t,123,6,43,58,NaN,NaN

In [476]:
df.isnull().sum()

DATE_TIME                   0
LONGITUDE                   0
LATITUDE                    0
GEOHASH                     0
MINIMUM_SPEED               0
MAXIMUM_SPEED               0
AVERAGE_SPEED               0
NUMBER_OF_VEHICLES          0
minimum hız           1338909
yüz_carpim            1338909
dtype: int64

In [477]:
print(df.columns)

Index(['DATE_TIME', 'LONGITUDE', 'LATITUDE', 'GEOHASH', 'MINIMUM_SPEED',
       'MAXIMUM_SPEED', 'AVERAGE_SPEED', 'NUMBER_OF_VEHICLES', 'minimum hız',
       'yüz_carpim'],
      dtype='object')

In [478]:
def temizlik_hatti(df):
    try:
        # Sütun isimlerini standartlaştır
        df.columns = df.columns.str.strip().str.replace(' ', '_').str.upper()
        
        # Artık 'MINIMUM_HIZ' yerine 'MINIMUM_SPEED' kullanmalısın
        ortalama_hiz = df['MINIMUM_SPEED'].mean()
        df['MINIMUM_SPEED'] = df['MINIMUM_SPEED'].fillna(ortalama_hiz)
        
        # Hatalı hızları düzelt
        df['MINIMUM_SPEED'] = df['MINIMUM_SPEED'].apply(lambda x: 0 if x < 0 else x)
        
        print("Temizlik başarıyla tamamlandı.")
        return df
    except Exception as e:
        print(f"Hata oluştu: {e}")
        return None

In [479]:
df=temizlik_hatti(df)
df.info()

Temizlik başarıyla tamamlandı.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338909 entries, 0 to 1338908
Data columns (total 10 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   DATE_TIME           1338909 non-null  object
 1   LONGITUDE           1338909 non-null  float64
 2   LATITUDE            1338909 non-null  float64
 3   GEOHASH             1338909 non-null  object
 4   MINIMUM_SPEED       1338909 non-null  int64
 5   MAXIMUM_SPEED       1338909 non-null  int64
 6   AVERAGE_SPEED       1338909 non-null  int64
 7   NUMBER_OF_VEHICLES  1338909 non-null  int64
 8   MINIMUM_HIZ         0 non-null        float64
 9   YÜZ_CARPIM          0 non-null        float64
dtypes: float64(4), int64(4), object(2)
memory usage: 102.2+ MB

In [480]:
df.describe()

,LONGITUDE,LATITUDE,MINIMUM_SPEED,MAXIMUM_SPEED,AVERAGE_SPEED,NUMBER_OF_VEHICLES,MINIMUM_HIZ,YÜZ_CARPIM
count,1.338909e+06,1.338909e+06,1.338909e+06,1.338909e+06,1.338909e+06,1.338909e+06,0.0,0.0
mean,2.888925e+01,4.106269e+01,9.856112e+01,2.547294e+01,5.748381e+01,3.537015e+01,NaN,NaN
std,3.543979e-01,1.008839e-01,3.661531e+01,2.554164e+01,2.601796e+01,6.900467e+01,NaN,NaN
min,2.796570e+01,4.076752e+01,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,NaN,NaN
25%,2.870178e+01,4.099823e+01,6.900000e+01,5.000000e+00,3.400000e+01,1.000000e+00,NaN,NaN
50%,2.893250e+01,4.105865e+01,9.700000e+01,1.200000e+01,5.500000e+01,1.000000e+00,NaN,NaN
75%,2.915222e+01,4.113007e+01,1.260000e+02,4.700000e+01,8.100000e+01,4.000000e+01,NaN,NaN
max,2.963562e+01,4.134430e+01,2.530000e+02,1.910000e+02,1.910000e+02,1.273000e+03,NaN,NaN

In [481]:
df.columns = df.columns.str.strip()
df['DATE_TIME']=pd.to_datetime(df['DATE_TIME'])
df['HOUR']=df['DATE_TIME'].dt.hour
saatlik_analiz=df.groupby('HOUR')['NUMBER_OF_VEHICLES'].mean()
print(saatlik_analiz)

HOUR
0     28.405850
1     22.537824
2     17.000000
3     14.811949
4     16.712587
5     28.789080
6     47.022542
7     45.966108
8     36.952283
9     33.422269
10    37.582851
11    34.130764
12    39.305675
13    39.081756
14    38.035908
15    36.729813
16    33.945258
17    39.027927
18    40.841058
19    46.548291
20    42.251059
21    40.452421
22    38.140595
23    36.519525
Name: NUMBER_OF_VEHICLES, dtype: float64

In [482]:
korelasyon=df[['NUMBER_OF_VEHICLES','AVERAGE_SPEED']].corr()
print("korelasyon matrisi:")
print(korelasyon)

korelasyon matrisi:
                    NUMBER_OF_VEHICLES  AVERAGE_SPEED
NUMBER_OF_VEHICLES            1.000000      -0.002191
AVERAGE_SPEED                -0.002191       1.000000

In [483]:
# Hızın en düşük olduğu (örneğin 20 km/s altı) bölgeleri filtrele
sikisiklik_noktalari = df[df['AVERAGE_SPEED'] < 20]

# Bu noktaların koordinatlarını al
koordinatlar = sikisiklik_noktalari[['LATITUDE', 'LONGITUDE']].head(10)

print("Trafiğin en yoğun (en yavaş) olduğu 10 koordinat noktası:")
print(koordinatlar)

Trafiğin en yoğun (en yavaş) olduğu 10 koordinat noktası:
      LATITUDE  LONGITUDE
15   40.998230  28.789673
65   41.025696  29.009399
102  41.047668  29.053345
197  41.025696  28.800659
263  41.234436  28.591919
333  41.075134  28.987427
404  41.058655  29.042358
461  40.976257  28.767700
491  41.327820  27.976685
550  41.020203  28.855591